# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d8f8e37953ef2d844a1ce1c3564626bdaca8622b2c813d05ec338c2afd315492c492ff98f8ababf6efddb941f4c11f831173aaad3d26b5060d19e9c70299d0

test:
  secret_key_base: 0856b238e1c1d1e49518c6306f4a8d285399b7f96b1fbf5ef200226abfa70db5db6ccc7759efe33f0db4ea359e4853970ce49824f1029cb7f28f24875a5070ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
